### ISSUE TITLE
First level key issues result in a crash

### ISSUE THREAD

**Issue by fbw218** [ZevEisenberg/UsefulDecode#3]
We found an issue where if you try to decode an object that has a misspelled key at the top level, the application will crash due to a force unwrap because `codingPath` is empty. ie 
```
{
  "feathers" : "some",
  "names" : "Big"
}
```
will crash because `names` != `name`. 

This fork should have the necessary fix. https://github.com/fbw218/UsefulDecode

**Comment by ZevEisenberg** [comment]
Thanks! I saw you opened #2 and then closed it - want to make a PR with the fix?

**Comment by fbw218** [comment]
Yeah - just opened a PR for it. If you could take a look, that would be awesome. Thanks!

**Comment by ZevEisenberg** [comment]
Closed by #4
